In [1]:
import pandas as pd
import numpy as np

import json

import re

import warnings
warnings.filterwarnings("ignore")

In [21]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [22]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from rake_nltk import Rake

In [23]:
FILEPATH="../data/cleaned/"

df = pd.read_csv(FILEPATH+"movie_data_cleaned.csv")

In [24]:
df.head()

,title,genres,keywords,overview
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [25]:
df.loc[0, 'genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [26]:
json.loads(df.loc[0, 'genres'])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

# Data Extraction

### Extracting genres and keywords and storing into dataset

In [27]:
def data_extraction(x):
    data_list = []
    x = json.loads(x)
    for i, item in enumerate(x):
        data_list.append(x[i]['name'])
    final_data = ', '.join(data_list)
    return final_data

In [28]:
df.loc[:, 'genres'] = df.loc[:, 'genres'].apply(lambda x: data_extraction(x))
df.loc[:, 'keywords'] = df.loc[:, 'keywords'].apply(lambda x: data_extraction(x))

In [29]:
df.head()

,title,genres,keywords,overview
0,Avatar,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",Following the death of District Attorney Harve...
4,John Carter,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...","John Carter is a war-weary, former military ca..."

In [30]:
df.isnull().sum()

title       0
genres      0
keywords    0
overview    3
dtype: int64

# Checking Available Genres:

In [31]:
x = df.loc[0,'genres']
x.split(', ')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [32]:
genres = set()
for i in df['genres']:
    i = i.split(', ')
    genres.update(i)

In [33]:
genres

{'',
 'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [34]:
genres.remove('')

In [35]:
genres

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [36]:
df['overview'] = df['overview'].fillna(value='')

In [37]:
df['overview'].isnull().sum() # no null values present

np.int64(0)

In [38]:
description = df.loc[0,'overview']
description

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [39]:
# customize stopwords according to your requirement
cust_stopwords = set(stopwords.words('english'))

### We are using Rake algorithm for quick text extraction

In [40]:
def text_extraction(x):
    r = Rake(stopwords=cust_stopwords)
    r.extract_keywords_from_text(x)
    keyword_score = r.get_word_degrees()
    res = ' '.join(list(keyword_score.keys()))
    return res

In [41]:
df.loc[:, 'overview'] = df.loc[:, 'overview'].apply(lambda x: text_extraction(x))

In [42]:
description = df.loc[0,'overview']
description

'22nd century paraplegic marine dispatched moon pandora unique mission becomes torn following orders protecting alien civilization'

In [43]:
df.head()

,title,genres,keywords,overview
0,Avatar,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",22nd century paraplegic marine dispatched moon...
1,Pirates of the Caribbean: At World's End,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",captain barbossa long believed dead come back ...
2,Spectre,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",cryptic message bond ’ past sends trail uncove...
3,The Dark Knight Rises,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",following death district attorney harvey dent ...
4,John Carter,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",john carter war weary former military captain ...

In [44]:
df = df.reset_index(drop=True)

In [45]:
for item in df.iterrows():
    print(item)

(0, title                                                  Avatar
genres            Action, Adventure, Fantasy, Science Fiction
keywords    culture clash, future, space war, space colony...
overview    22nd century paraplegic marine dispatched moon...
Name: 0, dtype: object)
(1, title                Pirates of the Caribbean: At World's End
genres                             Adventure, Fantasy, Action
keywords    ocean, drug abuse, exotic island, east india t...
overview    captain barbossa long believed dead come back ...
Name: 1, dtype: object)
(2, title                                                 Spectre
genres                               Action, Adventure, Crime
keywords    spy, based on novel, secret agent, sequel, mi6...
overview    cryptic message bond ’ past sends trail uncove...
Name: 2, dtype: object)
(3, title                                   The Dark Knight Rises
genres                         Action, Crime, Drama, Thriller
keywords    dc comics, crime fighter, terrorist, secret id...
overview    following death district attorney harvey dent ...
Name: 3, dtype: object)
(4, title                                             John Carter
genres                     Action, Adventure, Science Fiction
keywords    based on novel, mars, medallion, space travel,...
overview    john carter war weary former military captain ...
Name: 4, dtype: object)
(5, title                                            Spider-Man 3
genres                             Fantasy, Action, Adventure
keywords    dual identity, amnesia, sandstorm, love of one...
overview    seemingly invincible spider man goes new crop ...
Name: 5, dtype: object)
(6, title                                                 Tangled
genres                                      Animation, Family
keywords    hostage, magic, horse, fairy tale, musical, pr...
overview    kingdom wanted charming bandit flynn rider hid...
Name: 6, dtype: object)
(7, title                                 Avengers: Age of Ultron
genres                     Action, Adventure, Science Fiction
keywords    marvel comic, sequel, superhero, based on comi...
overview    tony stark tries jumpstart dormant peacekeepin...
Name: 7, dtype: object)
(8, title                  Harry Potter and the Half-Blood Prince
genres                             Adventure, Fantasy, Family
keywords    witch, magic, broom, school of witchcraft, wiz...
overview    harry begins sixth year hogwarts discovers old...
Name: 8, dtype: object)
(9, title                      Batman v Superman: Dawn of Justice
genres                             Action, Adventure, Fantasy
keywords    dc comics, vigilante, superhero, based on comi...
overview    fearing actions god like super hero left unche...
Name: 9, dtype: object)
(10, title                                        Superman Returns
genres            Adventure, Fantasy, Action, Science Fiction
keywords    saving the world, dc comics, invulnerability, ...
overview    superman returns discover 5 year absence allow...
Name: 10, dtype: object)
(11, title                                       Quantum of Solace
genres                     Adventure, Action, Thriller, Crime
keywords    killing, undercover, secret agent, british sec...
overview    quantum solace continues adventures james bond...
Name: 11, dtype: object)
(12, title              Pirates of the Caribbean: Dead Man's Chest
genres                             Adventure, Fantasy, Action
keywords    witch, fortune teller, bondage, exotic island,...
overview    captain jack sparrow works way blood debt ghos...
Name: 12, dtype: object)
(13, title                                         The Lone Ranger
genres                             Action, Adventure, Western
keywords    texas, horse, survivor, texas ranger, partner,...
overview    texas rangers chase gang outlaws led butch cav...
Name: 13, dtype: object)
(14, title                                            Man of Steel
genres            Action, Adventure, Fantasy, Science Fiction
keywords    saving the world, dc comics, superhero, based ...
overview    young boy learns extraordinary powers earth ma...
Name: 14, dtype: object)
(15, title                The Chronicles of Narnia: Prince Caspian
genres                             Adventure, Family, Fantasy
keywords    based on novel, fictional place, brother siste...
overview    one year incredible adventures lion witch ward...
Name: 15, dtype: object)
(16, title                                            The Avengers
genres                     Science Fiction, Action, Adventure
keywords    new york, shield, marvel comic, superhero, bas...
overview    unexpected enemy emerges threatens global safe...
Name: 16, dtype: object)
(17, title             Pirates of the Caribbean: On Stranger Tides
genres                             Adventure, Action, Fantasy
keywords    sea, captain, mutiny, sword, prime minister, s...
overview    captain jack sparrow crosses paths woman past ...
Name: 17, dtype: object)
(18, title                                          Men in Black 3
genres                        Action, Comedy, Science Fiction
keywords    time travel, time machine, alien, fictional go...
overview    agents j smith k tommy lee jones back ... time...
Name: 18, dtype: object)
(19, title               The Hobbit: The Battle of the Five Armies
genres                             Action, Adventure, Fantasy
keywords    corruption, elves, dwarves, orcs, middle-earth...
overview    immediately events desolation smaug bilbo dwar...
Name: 19, dtype: object)
(20, title                                  The Amazing Spider-Man
genres                             Action, Adventure, Fantasy
keywords    loss of father, vigilante, serum, marvel comic...
overview    peter parker outcast high schooler abandoned p...
Name: 20, dtype: object)
(21, title                                              Robin Hood
genres                                      Action, Adventure
keywords    robin hood, archer, knight, sherwood forest, b...
overview    soldier robin happens upon dying robert loxley...
Name: 21, dtype: object)
(22, title                     The Hobbit: The Desolation of Smaug
genres                                     Adventure, Fantasy
keywords    elves, dwarves, orcs, hobbit, dragon, wizard, ...
overview    dwarves bilbo gandalf successfully escaped mis...
Name: 22, dtype: object)
(23, title                                      The Golden Compass
genres                                     Adventure, Fantasy
keywords    england, compass, experiment, lordship, uncle,...
overview    overhearing shocking secret precocious orphan ...
Name: 23, dtype: object)
(24, title                                               King Kong
genres                               Adventure, Drama, Action
keywords    film business, screenplay, show business, film...
overview    1933 new york overly ambitious movie producer ...
Name: 24, dtype: object)
(25, title                                                 Titanic
genres                               Drama, Romance, Thriller
keywords    shipwreck, iceberg, ship, panic, titanic, ocea...
overview    84 years later 101 year old woman named rose d...
Name: 25, dtype: object)
(26, title                              Captain America: Civil War
genres                     Adventure, Action, Science Fiction
keywords    civil war, war, marvel comic, sequel, superher...
overview    following events age ultron collective governm...
Name: 26, dtype: object)
(27, title                                              Battleship
genres           Thriller, Action, Adventure, Science Fiction
keywords    fight, u.s. navy, mind reading, hong kong, soc...
overview    mankind beams radio signal space reply comes ‘...
Name: 27, dtype: object)
(28, title                                          Jurassic World
genres           Action, Adventure, Science Fiction, Thriller
keywords    monster, dna, tyrannosaurus rex, velociraptor,...
overview    twenty two years events jurassic park isla nub...
Name: 28, dtype: object)
(29, title                                                 Skyfall
genres                            Action, Adventure, Thriller
keywords    spy, secret agent, sociopath, killer, art gall...
overview    bond latest assignment goes gravely wrong agen...
Name: 29, dtype: object)
(30, title                                            Spider-Man 2
genres                             Action, Adventure, Fantasy
keywords    dual identity, love of one's life, pizza boy, ...
overview    peter parker going major identity crisis burne...
Name: 30, dtype: object)
(31, title                                              Iron Man 3
genres                     Action, Adventure, Science Fiction
keywords    terrorist, war on terror, tennessee, malibu, m...
overview    tony stark world torn apart formidable terrori...
Name: 31, dtype: object)
(32, title                                     Alice in Wonderland
genres                             Family, Fantasy, Adventure
keywords    based on novel, fictional place, queen, fantas...
overview    alice unpretentious individual 19 year old bet...
Name: 32, dtype: object)
(33, title                                   X-Men: The Last Stand
genres           Adventure, Action, Science Fiction, Thriller
keywords    mutant, marvel comic, based on comic book, sup...
overview    cure found treat mutations lines drawn amongst...
Name: 33, dtype: object)
(34, title                                     Monsters University
genres                                      Animation, Family
keywords    monster, dormitory, games, animation, best fri...
overview    look relationship mike sulley days monsters un...
Name: 34, dtype: object)
(35, title                     Transformers: Revenge of the Fallen
genres                     Science Fiction, Action, Adventure
keywords    egypt, sun, chaos, symbol, artifact, transform...
overview    sam witwicky leaves autobots behind normal lif...
Name: 35, dtype: object)
(36, title                         Transformers: Age of Extinction
genres                     Science Fiction, Action, Adventure
keywords    sequel, alien, transformers, giant robot, robo...
overview    humanity picks pieces following conclusion tra...
Name: 36, dtype: object)
(37, title                              Oz: The Great and Powerful
genres                             Fantasy, Adventure, Family
keywords    circus, witch, magic, hope, illusion, lost, ma...
overview    oscar diggs small time circus illusionist con ...
Name: 37, dtype: object)
(38, title                                The Amazing Spider-Man 2
genres                             Action, Adventure, Fantasy
keywords    obsession, marvel comic, sequel, based on comi...
overview    peter parker life busy taking bad guys spider ...
Name: 38, dtype: object)
(39, title                                            TRON: Legacy
genres                     Adventure, Action, Science Fiction
keywords    artificial intelligence, secret identity, comp...
overview    sam flynn tech savvy daring son kevin investig...
Name: 39, dtype: object)
(40, title                                                  Cars 2
genres                   Animation, Family, Adventure, Comedy
keywords    car race, sequel, comedy, anthropomorphism, be...
overview    star race car lightning mcqueen pal mater head...
Name: 40, dtype: object)
(41, title                                           Green Lantern
genres           Adventure, Action, Thriller, Science Fiction
keywords    dc comics, transformation, superhero, alien, a...
overview    centuries small powerful force warriors called...
Name: 41, dtype: object)
(42, title                                             Toy Story 3
genres                              Animation, Family, Comedy
keywords    hostage, college, toy, barbie, animation, esca...
overview    woody buzz rest andy toys played years go coll...
Name: 42, dtype: object)
(43, title                                    Terminator Salvation
genres                      Action, Science Fiction, Thriller
keywords    saving the world, artificial intelligence, pro...
overview    grown post apocalyptic 2018 john connor must l...
Name: 43, dtype: object)
(44, title                                               Furious 7
genres                                                 Action
keywords    car race, speed, revenge, suspense, car, race,...
overview    deckard shaw seeks revenge dominic toretto fam...
Name: 44, dtype: object)
(45, title                                             World War Z
genres       Action, Drama, Horror, Science Fiction, Thriller
keywords    dystopia, apocalypse, zombie, nuclear weapons,...
overview    life former united nations investigator gerry ...
Name: 45, dtype: object)
(46, title                              X-Men: Days of Future Past
genres            Action, Adventure, Fantasy, Science Fiction
keywords    1970s, mutant, time travel, marvel comic, base...
overview    ultimate x men ensemble fights war survival sp...
Name: 46, dtype: object)
(47, title                                 Star Trek Into Darkness
genres                     Action, Adventure, Science Fiction
keywords    spacecraft, friendship, sequel, futuristic, sp...
overview    crew enterprise called back home find unstoppa...
Name: 47, dtype: object)
(48, title                                   Jack the Giant Slayer
genres                                Action, Family, Fantasy
keywords                           based on fairy tale, giant
overview    story ancient war reignited young farmhand unw...
Name: 48, dtype: object)
(49, title                                        The Great Gatsby
genres                                         Drama, Romance
keywords      based on novel, infidelity, obsession, hope, 3d
overview    adaptation f scott fitzgerald long island set ...
Name: 49, dtype: object)
(50, title                     Prince of Persia: The Sands of Time
genres                    Adventure, Fantasy, Action, Romance
keywords    persia, sandstorm, brother against brother, ar...
overview    rogue prince reluctantly joins forces mysterio...
Name: 50, dtype: object)
(51, title                                             Pacific Rim
genres                     Action, Science Fiction, Adventure
keywords    dystopia, giant robot, giant monster, apocalyp...
overview    legions monstrous creatures known kaiju starte...
Name: 51, dtype: object)
(52, title                          Transformers: Dark of the Moon
genres                     Action, Science Fiction, Adventure
keywords    moon, spacecraft, traitor, bodyguard, alien pl...
overview    sam witwicky takes first tenuous steps adultho...
Name: 52, dtype: object)
(53, title       Indiana Jones and the Kingdom of the Crystal S...
genres                                      Adventure, Action
keywords    saving the world, riddle, whip, treasure, mexi...
overview    set cold war soviets – led sword wielding irin...
Name: 53, dtype: object)
(54, title                                       The Good Dinosaur
genres                           Adventure, Animation, Family
keywords    tyrannosaurus rex, friends, alternate history,...
overview    epic journey world dinosaurs apatosaurus named...
Name: 54, dtype: object)
(55, title                                                   Brave
genres      Animation, Adventure, Comedy, Family, Action, ...
keywords    scotland, rebel, bravery, kingdom, archer, wis...
overview    brave set mystical scottish highlands mérida p...
Name: 55, dtype: object)
(56, title                                        Star Trek Beyond
genres                     Action, Adventure, Science Fiction
keywords                sequel, stranded, hatred, space opera
overview    uss enterprise crew explores furthest reaches ...
Name: 56, dtype: object)
(57, title                                                  WALL·E
genres                                      Animation, Family
keywords                                      romantic comedy
overview    wall · e last robot left earth overrun garbage...
Name: 57, dtype: object)
(58, title                                             Rush Hour 3
genres                        Action, Comedy, Crime, Thriller
keywords                                           ambassador
overview    attempted assassination ambassador han inspect...
Name: 58, dtype: object)
(59, title                                                    2012
genres                     Action, Adventure, Science Fiction
keywords    civilization, natural disaster, end of the wor...
overview    dr adrian helmsley part worldwide geophysical ...
Name: 59, dtype: object)
(60, title                                       A Christmas Carol
genres                                       Animation, Drama
keywords    holiday, based on novel, victorian england, mo...
overview    miser ebenezer scrooge awakened christmas eve ...
Name: 60, dtype: object)
(61, title                                       Jupiter Ascending
genres            Science Fiction, Fantasy, Action, Adventure
keywords    jupiter, space, woman director, 3d, interspeci...
overview    universe human genetic material precious commo...
Name: 61, dtype: object)
(62, title                                    The Legend of Tarzan
genres                                      Action, Adventure
keywords    africa, feral child, tarzan, jungle, animal at...
overview    tarzan acclimated life london called back form...
Name: 62, dtype: object)
(63, title       The Chronicles of Narnia: The Lion, the Witch ...
genres                             Adventure, Family, Fantasy
keywords    saving the world, witch, based on novel, broth...
overview    siblings lucy edmund susan peter step magical ...
Name: 63, dtype: object)
(64, title                                       X-Men: Apocalypse
genres                                        Science Fiction
keywords    mutant, supernatural powers, marvel comic, sup...
overview    emergence world first mutant destroyer apocaly...
Name: 64, dtype: object)
(65, title                                         The Dark Knight
genres                         Drama, Action, Crime, Thriller
keywords    dc comics, crime fighter, secret identity, sca...
overview    batman raises stakes war crime help lt jim gor...
Name: 65, dtype: object)
(66, title                                                      Up
genres                   Animation, Comedy, Family, Adventure
keywords    age difference, central and south america, bal...
overview    carl fredricksen spent entire life dreaming ex...
Name: 66, dtype: object)
(67, title                                      Monsters vs Aliens
genres          Animation, Family, Adventure, Science Fiction
keywords             alien, giant robot, duringcreditsstinger
overview    susan murphy unwittingly clobbered meteor full...
Name: 67, dtype: object)
(68, title                                                Iron Man
genres                     Action, Science Fiction, Adventure
keywords    middle east, arms dealer, malibu, marvel comic...
overview    held captive afghan cave billionaire engineer ...
Name: 68, dtype: object)
(69, title                                                    Hugo
genres                               Adventure, Drama, Family
keywords    library, clock, film director, key, toy, boy, ...
overview    hugo orphan boy living walls train station 193...
Name: 69, dtype: object)
(70, title                                          Wild Wild West
genres      Action, Adventure, Comedy, Science Fiction, We...
keywords    steampunk, based on tv series, steam locomotiv...
overview    legless southern inventor dr arliss loveless p...
Name: 70, dtype: object)
(71, title                   The Mummy: Tomb of the Dragon Emperor
genres                             Adventure, Action, Fantasy
keywords
overview    archaeologist rick connell travels china pitti...
Name: 71, dtype: object)

In [46]:
for index, row in df.iterrows():
    print("{}\n\n{}\n".format(index, row))

0

title                                                  Avatar
genres            Action, Adventure, Fantasy, Science Fiction
keywords    culture clash, future, space war, space colony...
overview    22nd century paraplegic marine dispatched moon...
Name: 0, dtype: object

1

title                Pirates of the Caribbean: At World's End
genres                             Adventure, Fantasy, Action
keywords    ocean, drug abuse, exotic island, east india t...
overview    captain barbossa long believed dead come back ...
Name: 1, dtype: object

2

title                                                 Spectre
genres                               Action, Adventure, Crime
keywords    spy, based on novel, secret agent, sequel, mi6...
overview    cryptic message bond ’ past sends trail uncove...
Name: 2, dtype: object

3

title                                   The Dark Knight Rises
genres                         Action, Crime, Drama, Thriller
keywords    dc comics, crime fighter, terrorist, secret id...
overview    following death district attorney harvey dent ...
Name: 3, dtype: object

4

title                                             John Carter
genres                     Action, Adventure, Science Fiction
keywords    based on novel, mars, medallion, space travel,...
overview    john carter war weary former military captain ...
Name: 4, dtype: object

5

title                                            Spider-Man 3
genres                             Fantasy, Action, Adventure
keywords    dual identity, amnesia, sandstorm, love of one...
overview    seemingly invincible spider man goes new crop ...
Name: 5, dtype: object

6

title                                                 Tangled
genres                                      Animation, Family
keywords    hostage, magic, horse, fairy tale, musical, pr...
overview    kingdom wanted charming bandit flynn rider hid...
Name: 6, dtype: object

7

title                                 Avengers: Age of Ultron
genres                     Action, Adventure, Science Fiction
keywords    marvel comic, sequel, superhero, based on comi...
overview    tony stark tries jumpstart dormant peacekeepin...
Name: 7, dtype: object

8

title                  Harry Potter and the Half-Blood Prince
genres                             Adventure, Fantasy, Family
keywords    witch, magic, broom, school of witchcraft, wiz...
overview    harry begins sixth year hogwarts discovers old...
Name: 8, dtype: object

9

title                      Batman v Superman: Dawn of Justice
genres                             Action, Adventure, Fantasy
keywords    dc comics, vigilante, superhero, based on comi...
overview    fearing actions god like super hero left unche...
Name: 9, dtype: object

10

title                                        Superman Returns
genres            Adventure, Fantasy, Action, Science Fiction
keywords    saving the world, dc comics, invulnerability, ...
overview    superman returns discover 5 year absence allow...
Name: 10, dtype: object

11

title                                       Quantum of Solace
genres                     Adventure, Action, Thriller, Crime
keywords    killing, undercover, secret agent, british sec...
overview    quantum solace continues adventures james bond...
Name: 11, dtype: object

12

title              Pirates of the Caribbean: Dead Man's Chest
genres                             Adventure, Fantasy, Action
keywords    witch, fortune teller, bondage, exotic island,...
overview    captain jack sparrow works way blood debt ghos...
Name: 12, dtype: object

13

title                                         The Lone Ranger
genres                             Action, Adventure, Western
keywords    texas, horse, survivor, texas ranger, partner,...
overview    texas rangers chase gang outlaws led butch cav...
Name: 13, dtype: object

14

title                                            Man of Steel
genres            Action, Adventure, Fantasy, Science Fiction
keywords    saving the world, dc comics, superhero, based ...
overview    young boy learns extraordinary powers earth ma...
Name: 14, dtype: object

15

title                The Chronicles of Narnia: Prince Caspian
genres                             Adventure, Family, Fantasy
keywords    based on novel, fictional place, brother siste...
overview    one year incredible adventures lion witch ward...
Name: 15, dtype: object

16

title                                            The Avengers
genres                     Science Fiction, Action, Adventure
keywords    new york, shield, marvel comic, superhero, bas...
overview    unexpected enemy emerges threatens global safe...
Name: 16, dtype: object

17

title             Pirates of the Caribbean: On Stranger Tides
genres                             Adventure, Action, Fantasy
keywords    sea, captain, mutiny, sword, prime minister, s...
overview    captain jack sparrow crosses paths woman past ...
Name: 17, dtype: object

18

title                                          Men in Black 3
genres                        Action, Comedy, Science Fiction
keywords    time travel, time machine, alien, fictional go...
overview    agents j smith k tommy lee jones back ... time...
Name: 18, dtype: object

19

title               The Hobbit: The Battle of the Five Armies
genres                             Action, Adventure, Fantasy
keywords    corruption, elves, dwarves, orcs, middle-earth...
overview    immediately events desolation smaug bilbo dwar...
Name: 19, dtype: object

20

title                                  The Amazing Spider-Man
genres                             Action, Adventure, Fantasy
keywords    loss of father, vigilante, serum, marvel comic...
overview    peter parker outcast high schooler abandoned p...
Name: 20, dtype: object

21

title                                              Robin Hood
genres                                      Action, Adventure
keywords    robin hood, archer, knight, sherwood forest, b...
overview    soldier robin happens upon dying robert loxley...
Name: 21, dtype: object

22

title                     The Hobbit: The Desolation of Smaug
genres                                     Adventure, Fantasy
keywords    elves, dwarves, orcs, hobbit, dragon, wizard, ...
overview    dwarves bilbo gandalf successfully escaped mis...
Name: 22, dtype: object

23

title                                      The Golden Compass
genres                                     Adventure, Fantasy
keywords    england, compass, experiment, lordship, uncle,...
overview    overhearing shocking secret precocious orphan ...
Name: 23, dtype: object

24

title                                               King Kong
genres                               Adventure, Drama, Action
keywords    film business, screenplay, show business, film...
overview    1933 new york overly ambitious movie producer ...
Name: 24, dtype: object

25

title                                                 Titanic
genres                               Drama, Romance, Thriller
keywords    shipwreck, iceberg, ship, panic, titanic, ocea...
overview    84 years later 101 year old woman named rose d...
Name: 25, dtype: object

26

title                              Captain America: Civil War
genres                     Adventure, Action, Science Fiction
keywords    civil war, war, marvel comic, sequel, superher...
overview    following events age ultron collective governm...
Name: 26, dtype: object

27

title                                              Battleship
genres           Thriller, Action, Adventure, Science Fiction
keywords    fight, u.s. navy, mind reading, hong kong, soc...
overview    mankind beams radio signal space reply comes ‘...
Name: 27, dtype: object

28

title                                          Jurassic World
genres           Action, Adventure, Science Fiction, Thriller
keywords    monster, dna, tyrannosaurus rex, velociraptor,...
overview    twenty two years events jurassic park isla nub...
Name: 28, dtype: object

29

title                                                 Skyfall
genres                            Action, Adventure, Thriller
keywords    spy, secret agent, sociopath, killer, art gall...
overview    bond latest assignment goes gravely wrong agen...
Name: 29, dtype: object

30

title                                            Spider-Man 2
genres                             Action, Adventure, Fantasy
keywords    dual identity, love of one's life, pizza boy, ...
overview    peter parker going major identity crisis burne...
Name: 30, dtype: object

31

title                                              Iron Man 3
genres                     Action, Adventure, Science Fiction
keywords    terrorist, war on terror, tennessee, malibu, m...
overview    tony stark world torn apart formidable terrori...
Name: 31, dtype: object

32

title                                     Alice in Wonderland
genres                             Family, Fantasy, Adventure
keywords    based on novel, fictional place, queen, fantas...
overview    alice unpretentious individual 19 year old bet...
Name: 32, dtype: object

33

title                                   X-Men: The Last Stand
genres           Adventure, Action, Science Fiction, Thriller
keywords    mutant, marvel comic, based on comic book, sup...
overview    cure found treat mutations lines drawn amongst...
Name: 33, dtype: object

34

title                                     Monsters University
genres                                      Animation, Family
keywords    monster, dormitory, games, animation, best fri...
overview    look relationship mike sulley days monsters un...
Name: 34, dtype: object

35

title                     Transformers: Revenge of the Fallen
genres                     Science Fiction, Action, Adventure
keywords    egypt, sun, chaos, symbol, artifact, transform...
overview    sam witwicky leaves autobots behind normal lif...
Name: 35, dtype: object

36

title                         Transformers: Age of Extinction
genres                     Science Fiction, Action, Adventure
keywords    sequel, alien, transformers, giant robot, robo...
overview    humanity picks pieces following conclusion tra...
Name: 36, dtype: object

37

title                              Oz: The Great and Powerful
genres                             Fantasy, Adventure, Family
keywords    circus, witch, magic, hope, illusion, lost, ma...
overview    oscar diggs small time circus illusionist con ...
Name: 37, dtype: object

38

title                                The Amazing Spider-Man 2
genres                             Action, Adventure, Fantasy
keywords    obsession, marvel comic, sequel, based on comi...
overview    peter parker life busy taking bad guys spider ...
Name: 38, dtype: object

39

title                                            TRON: Legacy
genres                     Adventure, Action, Science Fiction
keywords    artificial intelligence, secret identity, comp...
overview    sam flynn tech savvy daring son kevin investig...
Name: 39, dtype: object

40

title                                                  Cars 2
genres                   Animation, Family, Adventure, Comedy
keywords    car race, sequel, comedy, anthropomorphism, be...
overview    star race car lightning mcqueen pal mater head...
Name: 40, dtype: object

41

title                                           Green Lantern
genres           Adventure, Action, Thriller, Science Fiction
keywords    dc comics, transformation, superhero, alien, a...
overview    centuries small powerful force warriors called...
Name: 41, dtype: object

42

title                                             Toy Story 3
genres                              Animation, Family, Comedy
keywords    hostage, college, toy, barbie, animation, esca...
overview    woody buzz rest andy toys played years go coll...
Name: 42, dtype: object

43

title                                    Terminator Salvation
genres                      Action, Science Fiction, Thriller
keywords    saving the world, artificial intelligence, pro...
overview    grown post apocalyptic 2018 john connor must l...
Name: 43, dtype: object

44

title                                               Furious 7
genres                                                 Action
keywords    car race, speed, revenge, suspense, car, race,...
overview    deckard shaw seeks revenge dominic toretto fam...
Name: 44, dtype: object

45

title                                             World War Z
genres       Action, Drama, Horror, Science Fiction, Thriller
keywords    dystopia, apocalypse, zombie, nuclear weapons,...
overview    life former united nations investigator gerry ...
Name: 45, dtype: object

46

title                              X-Men: Days of Future Past
genres            Action, Adventure, Fantasy, Science Fiction
keywords    1970s, mutant, time travel, marvel comic, base...
overview    ultimate x men ensemble fights war survival sp...
Name: 46, dtype: object

47

title                                 Star Trek Into Darkness
genres                     Action, Adventure, Science Fiction
keywords    spacecraft, friendship, sequel, futuristic, sp...
overview    crew enterprise called back home find unstoppa...
Name: 47, dtype: object

48

title                                   Jack the Giant Slayer
genres                                Action, Family, Fantasy
keywords                           based on fairy tale, giant
overview    story ancient war reignited young farmhand unw...
Name: 48, dtype: object

49

title                                        The Great Gatsby
genres                                         Drama, Romance
keywords      based on novel, infidelity, obsession, hope, 3d
overview    adaptation f scott fitzgerald long island set ...
Name: 49, dtype: object

50

title                     Prince of Persia: The Sands of Time
genres                    Adventure, Fantasy, Action, Romance
keywords    persia, sandstorm, brother against brother, ar...
overview    rogue prince reluctantly joins forces mysterio...
Name: 50, dtype: object

51

title                                             Pacific Rim
genres                     Action, Science Fiction, Adventure
keywords    dystopia, giant robot, giant monster, apocalyp...
overview    legions monstrous creatures known kaiju starte...
Name: 51, dtype: object

52

title                          Transformers: Dark of the Moon
genres                     Action, Science Fiction, Adventure
keywords    moon, spacecraft, traitor, bodyguard, alien pl...
overview    sam witwicky takes first tenuous steps adultho...
Name: 52, dtype: object

53

title       Indiana Jones and the Kingdom of the Crystal S...
genres                                      Adventure, Action
keywords    saving the world, riddle, whip, treasure, mexi...
overview    set cold war soviets – led sword wielding irin...
Name: 53, dtype: object

54

title                                       The Good Dinosaur
genres                           Adventure, Animation, Family
keywords    tyrannosaurus rex, friends, alternate history,...
overview    epic journey world dinosaurs apatosaurus named...
Name: 54, dtype: object

55

title                                                   Brave
genres      Animation, Adventure, Comedy, Family, Action, ...
keywords    scotland, rebel, bravery, kingdom, archer, wis...
overview    brave set mystical scottish highlands mérida p...
Name: 55, dtype: object

56

title                                        Star Trek Beyond
genres                     Action, Adventure, Science Fiction
keywords                sequel, stranded, hatred, space opera
overview    uss enterprise crew explores furthest reaches ...
Name: 56, dtype: object

57

title                                                  WALL·E
genres                                      Animation, Family
keywords                                      romantic comedy
overview    wall · e last robot left earth overrun garbage...
Name: 57, dtype: object

58

title                                             Rush Hour 3
genres                        Action, Comedy, Crime, Thriller
keywords                                           ambassador
overview    attempted assassination ambassador han inspect...
Name: 58, dtype: object

59

title                                                    2012
genres                     Action, Adventure, Science Fiction
keywords    civilization, natural disaster, end of the wor...
overview    dr adrian helmsley part worldwide geophysical ...
Name: 59, dtype: object

60

title                                       A Christmas Carol
genres                                       Animation, Drama
keywords    holiday, based on novel, victorian england, mo...
overview    miser ebenezer scrooge awakened christmas eve ...
Name: 60, dtype: object

61

title                                       Jupiter Ascending
genres            Science Fiction, Fantasy, Action, Adventure
keywords    jupiter, space, woman director, 3d, interspeci...
overview    universe human genetic material precious commo...
Name: 61, dtype: object

62

title                                    The Legend of Tarzan
genres                                      Action, Adventure
keywords    africa, feral child, tarzan, jungle, animal at...
overview    tarzan acclimated life london called back form...
Name: 62, dtype: object

63

title       The Chronicles of Narnia: The Lion, the Witch ...
genres                             Adventure, Family, Fantasy
keywords    saving the world, witch, based on novel, broth...
overview    siblings lucy edmund susan peter step magical ...
Name: 63, dtype: object

64

title                                       X-Men: Apocalypse
genres                                        Science Fiction
keywords    mutant, supernatural powers, marvel comic, sup...
overview    emergence world first mutant destroyer apocaly...
Name: 64, dtype: object

65

title                                         The Dark Knight
genres                         Drama, Action, Crime, Thriller
keywords    dc comics, crime fighter, secret identity, sca...
overview    batman raises stakes war crime help lt jim gor...
Name: 65, dtype: object

66

title                                                      Up
genres                   Animation, Comedy, Family, Adventure
keywords    age difference, central and south america, bal...
overview    carl fredricksen spent entire life dreaming ex...
Name: 66, dtype: object

67

title                                      Monsters vs Aliens
genres          Animation, Family, Adventure, Science Fiction
keywords             alien, giant robot, duringcreditsstinger
overview    susan murphy unwittingly clobbered meteor full...
Name: 67, dtype: object

68

title                                                Iron Man
genres                     Action, Science Fiction, Adventure
keywords    middle east, arms dealer, malibu, marvel comic...
overview    held captive afghan cave billionaire engineer ...
Name: 68, dtype: object

69

title                                                    Hugo
genres                               Adventure, Drama, Family
keywords    library, clock, film director, key, toy, boy, ...
overview    hugo orphan boy living walls train station 193...
Name: 69, dtype: object

70

title                                          Wild Wild West
genres      Action, Adventure, Comedy, Science Fiction, We...
keywords    steampunk, based on tv series, steam locomotiv...
overview    legless southern inventor dr arliss loveless p...
Name: 70, dtype: object

71

title                   The Mummy: Tomb of the Dragon Emperor
genres                             Adventure, Action, Fantasy
keywords
overview    archaeologist rick connell travels china pitti...
Name: 71, dtype: object

72

title                                           Suicide Squad
genres      Action, Adventure, Crime, Fantasy, Science Fic...

``` python
df['meta_tags'] = '' # creating an empty column


for index, row in df.iterrows():
    #meta tags
    genre = row['genres'].replace(',', '').lower()
    keyword = row['keywords'].replace(',', '').lower()
    overview = row['overview'].lower()
    overview_filtered = re.sub(pattern="[^a-z0-9 ]+", repl="", string=overview)

    # combine all features in to meta tags - string concatination
    combined_keywords = genre+' '+keyword+' '+overview_filtered

    df.at[index, 'meta_tags'] = combined_keywords
```

### Creating weighted meta data

In [47]:
# clean columns
df['genres_clean'] = df['genres'].str.replace(',', '', regex=False).str.lower()
df['keywords_clean'] = df['keywords'].str.replace(',', '', regex=False).str.lower()

df['overview_clean'] = (
    df['overview']
    .str.lower()
    .str.replace(r'[^a-z0-9 ]+', '', regex=True)
)

# combine into meta_tags
df['meta_tags'] = (
    df['genres_clean'] + ' ' +
    df['keywords_clean'] + ' ' +
    df['overview_clean']
)

In [48]:
df.head()

,title,genres,keywords,overview,genres_clean,keywords_clean,overview_clean,meta_tags
0,Avatar,"Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...",22nd century paraplegic marine dispatched moon...,action adventure fantasy science fiction,culture clash future space war space colony so...,22nd century paraplegic marine dispatched moon...,action adventure fantasy science fiction cultu...
1,Pirates of the Caribbean: At World's End,"Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...",captain barbossa long believed dead come back ...,adventure fantasy action,ocean drug abuse exotic island east india trad...,captain barbossa long believed dead come back ...,adventure fantasy action ocean drug abuse exot...
2,Spectre,"Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...",cryptic message bond ’ past sends trail uncove...,action adventure crime,spy based on novel secret agent sequel mi6 bri...,cryptic message bond past sends trail uncover...,action adventure crime spy based on novel secr...
3,The Dark Knight Rises,"Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...",following death district attorney harvey dent ...,action crime drama thriller,dc comics crime fighter terrorist secret ident...,following death district attorney harvey dent ...,action crime drama thriller dc comics crime fi...
4,John Carter,"Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...",john carter war weary former military captain ...,action adventure science fiction,based on novel mars medallion space travel pri...,john carter war weary former military captain ...,action adventure science fiction based on nove...

In [49]:
df.loc[0,'meta_tags']

'action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d 22nd century paraplegic marine dispatched moon pandora unique mission becomes torn following orders protecting alien civilization'

In [50]:
df_meta = df[['title', 'meta_tags']]

### We are using lemmatization as lexicon normalization instead of using stemming because meta data is sensitive and needs to be clipped carefully without changing the meaning.

In [51]:
def lemmatizer_word(x):
    lemm_obj = WordNetLemmatizer()
    word_tokens = nltk.word_tokenize(text=x, language='english', preserve_line=False)
    lemm_words = []
    for i in word_tokens:
        lemm_words.append(lemm_obj.lemmatize(i))
    res = ' '.join(lemm_words)
    return res

In [52]:
df_meta.loc[:, 'meta_tags'] = df_meta.loc[:, 'meta_tags'].apply(lambda x: lemmatizer_word(x))

In [53]:
df_meta.loc[0, 'meta_tags']

'action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relation mind and soul 3d 22nd century paraplegic marine dispatched moon pandora unique mission becomes torn following order protecting alien civilization'

### Exporting file

In [54]:
EXPORT_FILEPATH="../data/train/"

df_meta.to_csv(EXPORT_FILEPATH+"meta_data.csv", index=False)